# Generated by Django 2.0.13 on 2019-06-18 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('namelist', '0002_auto_20190617_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='namelist.Persona')),
                ('CheckIn', models.DateTimeField(verbose_name='Check in')),
                ('CheckOut', models.DateTimeField(verbose_name='Check out')),
            ],
            bases=('namelist.persona',),
        ),
    ]
